### ISSUE TITLE
 The training suddenly stopped midway.

### ISSUE THREAD

**Issue by gesen2egee** [LoganBooker/prodigy-plus-schedule-free#4]
I think it was caused by the modifications to prodigy_steps.

Traceback (most recent call last):
  File "D:\SDXL\sd-scripts\sdxl_train_network.py", line 228, in <module>
    trainer.train(args)
  File "D:\SDXL\sd-scripts\train_network.py", line 1243, in train
    optimizer.step()
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\accelerate\optimizer.py", line 170, in step
    self.optimizer.step(closure)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\torch\optim\optimizer.py", line 484, in wrapper
    out = func(*args, **kwargs)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\prodigyplus\prodigy_plus_schedulefree.py", line 553, in step
    self.step_param(p, param_group)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\prodigyplus\prodigy_plus_schedulefree.py", line 520, in step_param
    if prodigy_steps > 0 and k == prodigy_steps:
UnboundLocalError: local variable 'prodigy_steps' referenced before assignment
steps:   0%|▏                                                      | 14/5000 [01:13<7:19:03,  5.28s/it, avr_loss=0.133]
Traceback (most recent call last):
  File "C:\Users\gesen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\gesen\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\SDXL\sd-scripts\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 1106, in launch_command
    simple_launcher(args)
  File "D:\SDXL\sd-scripts\venv\lib\site-packages\accelerate\commands\launch.py", line 704, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by LoganBooker** [comment]
@gesen2egee Thanks for the report. That should be fixed as of the latest commit.
